"""initial

Revision ID: 1f7bd6fc460d
Revises: 
Create Date: 2026-06-15 22:47:29.808270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f7bd6fc460d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_amenities')),
    sa.UniqueConstraint('name', name=op.f('uq_amenities_name'))
    )
    op.create_table('hosts',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hosts'))
    )
    op.create_table('regions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regions')),
    sa.UniqueConstraint('name', name=op.f('uq_regions_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_regions_slug'))
    )
    op.create_table('users',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('homesteads',
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_per_night', sa.Integer(), nullable=False),
    sa.Column('base_guests', sa.Integer(), nullable=False),
    sa.Column('extra_guest_fee', sa.Integer(), nullable=False),
    sa.Column('max_guests', sa.Integer(), nullable=False),
    sa.Column('cleaning_fee', sa.Integer(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('beds', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], name=op.f('fk_homesteads_host_id_hosts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name=op.f('fk_homesteads_region_id_regions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_homesteads'))
    )
    op.create_index(op.f('ix_homesteads_region_id'), 'homesteads', ['region_id'], unique=False)
    op.create_table('bookings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('homestead_id', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('accommodation_total', sa.Integer(), nullable=False),
    sa.Column('cleaning_fee', sa.Integer(), nullable=False),
    sa.Column('service_fee', sa.Integer(), nullable=False),
    sa.Column('donation_pct', sa.Float(), nullable=False),
    sa.Column('donation_amount', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['homestead_id'], ['homesteads.id'], name=op.f('fk_bookings_homestead_id_homesteads')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings'))
    )
    op.create_index(op.f('ix_bookings_homestead_id'), 'bookings', ['homestead_id'], unique=False)
    op.create_index(op.f('ix_bookings_stripe_session_id'), 'bookings', ['stripe_session_id'], unique=True)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('favourites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('homestead_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['homestead_id'], ['homesteads.id'], name=op.f('fk_favourites_homestead_id_homesteads')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favourites_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favourites')),
    sa.UniqueConstraint('user_id', 'homestead_id', name=op.f('uq_favourites_user_id'))
    )
    op.create_table('homestead_amenity',
    sa.Column('homestead_id', sa.Integer(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], name=op.f('fk_homestead_amenity_amenity_id_amenities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['homestead_id'], ['homesteads.id'], name=op.f('fk_homestead_amenity_homestead_id_homesteads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('homestead_id', 'amenity_id', name=op.f('pk_homestead_amenity'))
    )
    op.create_table('homestead_photos',
    sa.Column('homestead_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['homestead_id'], ['homesteads.id'], name=op.f('fk_homestead_photos_homestead_id_homesteads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_homestead_photos'))
    )
    op.create_table('reviews',
    sa.Column('homestead_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['homestead_id'], ['homesteads.id'], name=op.f('fk_reviews_homestead_id_homesteads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('homestead_photos')
    op.drop_table('homestead_amenity')
    op.drop_table('favourites')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_stripe_session_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_homestead_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_homesteads_region_id'), table_name='homesteads')
    op.drop_table('homesteads')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('regions')
    op.drop_table('hosts')
    op.drop_table('amenities')
    # ### end Alembic commands ###
