"""add homestead short_description

Revision ID: 2f1051d34644
Revises: b091b935e327
Create Date: 2026-07-01 13:55:25.421623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f1051d34644'
down_revision: Union[str, Sequence[str], None] = 'b091b935e327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homesteads', sa.Column('short_description', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homesteads', 'short_description')
    # ### end Alembic commands ###
