"""add unique constraint to host email

Revision ID: 70f8b6d7b3c4
Revises: 1f7bd6fc460d
Create Date: 2026-06-23 14:25:20.961575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70f8b6d7b3c4'
down_revision: Union[str, Sequence[str], None] = '1f7bd6fc460d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_hosts_email'), 'hosts', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_hosts_email'), 'hosts', type_='unique')
    # ### end Alembic commands ###
