"""add homestead location

Revision ID: b091b935e327
Revises: 70f8b6d7b3c4
Create Date: 2026-06-24 15:37:10.455335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b091b935e327'
down_revision: Union[str, Sequence[str], None] = '70f8b6d7b3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homesteads', sa.Column('location', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('homesteads', 'location')
    # ### end Alembic commands ###
